### ISSUE TITLE
Footer change triggers hot-reload several times

### ISSUE THREAD

**Issue by amaralDaniel** [joaosaro/staro-webkit#1]
After changing something in footer.pug, there was a BrowserSync triggered several times. Happened in the hero too.

**Comment by joaosaro** [comment]
Thanks Daniels. It's resolved with few changes in gulpfile.js, mostly watch task dependencies and split tasks.
There is a issue only in Windows when I was opening files with Atom - it was triggering watch tasks without any change in file.
